openapi: "3.0.0"
info:
  version: 1.0.0
  title: GarageFlow App API
  description: GarageFlow App backend API scaffold.
servers:
  - url: http://localhost:1337/api
paths: {}

components:
  schemas:
    ErrorDefault:
      $ref: 'schemas/error-default.yaml'
    Error400:
      $ref: 'schemas/error-400.yaml'
